"""Generate evidence-grounded robotic-system blueprints and diagnostics."""

# ruff: noqa: E501

from __future__ import annotations

import html
import json
import os
import re
import shutil
import socket
import subprocess
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, cast

_ANTHROPIC_ENDPOINT = "https://api.anthropic.com/v1/messages"
_ANTHROPIC_VERSION = "2023-06-01"
_DEFAULT_MODEL = "claude-sonnet-5"
_DEFAULT_EFFORT = "medium"
_MAX_OUTPUT_TOKENS = 12_000
_MAX_PROBES = 4
_MAX_PROBE_OUTPUT = 12_000


@dataclass(frozen=True, slots=True)
class AgentReportPaths:
    """Paths generated by one agentic analysis."""

    blueprint: Path
    diagnostics: Path
    analysis: Path


@dataclass(slots=True)
class DiagnosticIssue:
    """One evidence-grounded problem and its repair guidance."""

    code: str
    title: str
    severity: str
    confidence: int
    observed: list[str] = field(default_factory=list)
    probable_causes: list[str] = field(default_factory=list)
    primary_approach: list[str] = field(default_factory=list)
    alternative_approaches: list[list[str]] = field(default_factory=list)
    diagnostic_commands: list[str] = field(default_factory=list)
    success_criteria: list[str] = field(default_factory=list)
    evidence_level: str = "VERIFIED"

    def to_dict(self) -> dict[str, object]:
        return {
            "code": self.code,
            "title": self.title,
            "severity": self.severity,
            "confidence": self.confidence,
            "evidence_level": self.evidence_level,
            "observed": self.observed,
            "probable_causes": self.probable_causes,
            "primary_approach": self.primary_approach,
            "alternative_approaches": self.alternative_approaches,
            "diagnostic_commands": self.diagnostic_commands,
            "success_criteria": self.success_criteria,
        }


@dataclass(frozen=True, slots=True)
class ProbeRequest:
    """A model-requested probe selected from a closed read-only catalog."""

    probe: str
    target: str | None
    reason: str


@dataclass(frozen=True, slots=True)
class ProbeResult:
    """Bounded output from one approved read-only probe."""

    probe: str
    target: str | None
    command: tuple[str, ...]
    state: str
    output: str

    def to_dict(self) -> dict[str, object]:
        return {
            "probe": self.probe,
            "target": self.target,
            "command": list(self.command),
            "state": self.state,
            "output": self.output,
        }


@dataclass(slots=True)
class AnalysisOutcome:
    """Structured result returned by the agentic orchestration layer."""

    paths: AgentReportPaths
    provider_status: str
    summary: str
    architecture_observations: list[str]
    unknowns: list[str]
    issues: list[DiagnosticIssue]
    probes: list[ProbeResult]


def analyze_snapshot_file(
    snapshot_path: Path,
    output_directory: Path,
    *,
    provider: str = "anthropic",
    model: str = _DEFAULT_MODEL,
    effort: str = _DEFAULT_EFFORT,
    investigate: bool = False,
    focus: str | None = None,
) -> AnalysisOutcome:
    """Analyze a saved snapshot and write the two user-facing HTML reports."""

    snapshot = _load_snapshot(snapshot_path)
    paths = AgentReportPaths(
        blueprint=output_directory / "system-blueprint.html",
        diagnostics=output_directory / "diagnostic-report.html",
        analysis=output_directory / "agent-analysis.json",
    )
    deterministic_issues = _deterministic_issues(snapshot)
    summary = _deterministic_summary(snapshot)
    observations = _architecture_observations(snapshot)
    unknowns = _unknowns(snapshot)
    probes: list[ProbeResult] = []
    provider_status = "deterministic analysis"

    if provider not in {"anthropic", "none"}:
        raise ValueError("provider must be one of: anthropic, none")
    if effort not in {"low", "medium", "high", "xhigh"}:
        raise ValueError("effort must be one of: low, medium, high, xhigh")

    if provider != "none":
        try:
            response = _anthropic_analysis(
                snapshot,
                deterministic_issues,
                model=model,
                effort=effort,
                focus=focus,
            )
        except AgentProviderError as exception:
            provider_status = f"Claude unavailable; deterministic fallback ({exception})"
        else:
            provider_status = f"Anthropic Claude model {model} (effort {effort})"
            summary = _clean_text(response.get("summary")) or summary
            observations = _string_list(response.get("architecture_observations")) or observations
            unknowns = _string_list(response.get("unknowns")) or unknowns
            deterministic_issues = _merge_agent_issues(
                deterministic_issues,
                response.get("issues"),
            )
            requests = _parse_probe_requests(response.get("probe_requests"))

            if investigate and requests:
                probes = _run_probe_requests(snapshot, requests)
                if probes:
                    try:
                        revised = _anthropic_analysis(
                            snapshot,
                            deterministic_issues,
                            model=model,
                            effort=effort,
                            focus=focus,
                            probe_results=probes,
                        )
                    except AgentProviderError:
                        provider_status += "; probe re-analysis unavailable"
                    else:
                        provider_status += f"; {len(probes)} read-only probes evaluated"
                        summary = _clean_text(revised.get("summary")) or summary
                        observations = (
                            _string_list(revised.get("architecture_observations")) or observations
                        )
                        unknowns = _string_list(revised.get("unknowns")) or unknowns
                        deterministic_issues = _merge_agent_issues(
                            deterministic_issues,
                            revised.get("issues"),
                        )

    output_directory.mkdir(parents=True, exist_ok=True)
    paths.blueprint.write_text(
        _build_blueprint_html(
            snapshot,
            summary=summary,
            observations=observations,
            unknowns=unknowns,
            provider_status=provider_status,
            focus=focus,
        ),
        encoding="utf-8",
    )
    paths.diagnostics.write_text(
        _build_diagnostic_html(
            snapshot,
            issues=deterministic_issues,
            probes=probes,
            provider_status=provider_status,
        ),
        encoding="utf-8",
    )
    paths.analysis.write_text(
        json.dumps(
            {
                "source_snapshot": str(snapshot_path),
                "provider_status": provider_status,
                "focus": focus,
                "summary": summary,
                "architecture_observations": observations,
                "unknowns": unknowns,
                "issues": [issue.to_dict() for issue in deterministic_issues],
                "read_only_probes": [probe.to_dict() for probe in probes],
                "repairs_executed": False,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return AnalysisOutcome(
        paths=paths,
        provider_status=provider_status,
        summary=summary,
        architecture_observations=observations,
        unknowns=unknowns,
        issues=deterministic_issues,
        probes=probes,
    )


class AgentProviderError(RuntimeError):
    """Raised when the configured model provider cannot return valid analysis."""


def _load_snapshot(path: Path) -> dict[str, Any]:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except OSError as exception:
        raise ValueError(f"cannot read snapshot: {exception}") from exception
    except json.JSONDecodeError as exception:
        raise ValueError(f"snapshot is not valid JSON: {exception}") from exception

    if not isinstance(raw, dict):
        raise ValueError("snapshot root must be a JSON object")
    required = {"identity", "operating_system", "cpu", "memory", "network", "findings"}
    missing = sorted(required - raw.keys())
    if missing:
        raise ValueError("snapshot is missing required fields: " + ", ".join(missing))
    return cast(dict[str, Any], raw)


def _deterministic_summary(snapshot: dict[str, Any]) -> str:
    identity = _mapping(snapshot.get("identity"))
    os_info = _mapping(snapshot.get("operating_system"))
    platform = _mapping(snapshot.get("platform"))
    ros = _ros_overview(snapshot)
    devices = _current_ros_device_names(snapshot)
    machine = platform.get("product_name") or platform.get("board_name") or "Linux computer"
    graph = ""
    if ros:
        graph = (
            f" The live ROS 2 graph contains {ros.get('nodes', 0)} nodes and "
            f"{ros.get('topics', 0)} topics."
        )
    device_text = f" ROS currently uses {', '.join(devices)}." if devices else ""
    return (
        f"{identity.get('hostname', 'This robotic computer')} is a {machine} running "
        f"{os_info.get('distribution', 'Linux')}.{graph}{device_text}"
    )


def _architecture_observations(snapshot: dict[str, Any]) -> list[str]:
    observations: list[str] = []
    ros = _ros_overview(snapshot)
    if ros:
        observations.append(
            "ROS 2 uses "
            f"{ros.get('middleware') or 'an unspecified DDS implementation'} on domain "
            f"{ros.get('domain_id') if ros.get('domain_id') is not None else 'unknown'}."
        )
    for device in _records(snapshot.get("ros_device_inventory"))[:12]:
        details = _mapping(device.get("details"))
        kind = details.get("kind") or device.get("name")
        node = details.get("ros_node") or details.get("hardware_node")
        channel = details.get("topics") or details.get("channel")
        physical = details.get("physical_component")
        chain = " → ".join(str(value) for value in (physical, node, channel) if value)
        if chain:
            observations.append(f"{kind}: {chain}")
    return observations


def _unknowns(snapshot: dict[str, Any]) -> list[str]:
    unknowns: list[str] = []
    for device in _records(snapshot.get("ros_device_inventory")):
        details = _mapping(device.get("details"))
        if not details.get("physical_component"):
            unknowns.append(
                f"{details.get('kind') or device.get('name')}: physical hardware is not proven."
            )
    for device in _records(snapshot.get("serial_devices")):
        if not device.get("stable_id_path"):
            unknowns.append(
                f"{device.get('port', 'Serial device')}: no stable by-id identity was found."
            )
    return _deduplicate_text(unknowns)


def _deterministic_issues(snapshot: dict[str, Any]) -> list[DiagnosticIssue]:
    issues: list[DiagnosticIssue] = []
    for finding in _records(snapshot.get("findings")):
        severity = str(finding.get("severity") or "info").lower()
        code = str(finding.get("code") or "UNCLASSIFIED_FINDING")
        if severity == "info" and code.endswith(("_HEALTHY", "_DETECTED", "_DISCOVERED")):
            continue
        summary = _clean_text(finding.get("summary")) or code.replace("_", " ").title()
        evidence = _clean_text(finding.get("evidence"))
        recommendation = _clean_text(finding.get("recommendation"))
        steps = _recommendation_steps(recommendation, code)
        issues.append(
            DiagnosticIssue(
                code=code,
                title=summary.removeprefix("[OK] "),
                severity=_severity_label(severity),
                confidence=100 if evidence else 85,
                observed=[evidence] if evidence else [summary],
                probable_causes=[_default_cause(code)],
                primary_approach=steps,
                diagnostic_commands=_commands_for_code(code, finding),
                success_criteria=[_success_for_code(code)],
                evidence_level="VERIFIED" if evidence else "CORRELATED",
            )
        )

    runtime = _ros_overview(snapshot)
    if runtime and str(runtime.get("state") or "").upper() in {"UNAVAILABLE", "FAILED"}:
        if not any(issue.code == "ROS_RUNTIME_UNAVAILABLE" for issue in issues):
            issues.append(
                DiagnosticIssue(
                    code="ROS_RUNTIME_UNAVAILABLE",
                    title="ROS 2 runtime graph could not be inspected",
                    severity="HIGH",
                    confidence=95,
                    observed=[f"ROS graph state: {runtime.get('state')}"],
                    probable_causes=[
                        "The scanner and ROS processes may use different environment or DDS settings."
                    ],
                    primary_approach=[
                        "Source the same ROS underlay and workspace used to launch the robot.",
                        "Verify ROS_DOMAIN_ID and RMW_IMPLEMENTATION.",
                        "Run ros2 node list and confirm that the graph is visible.",
                        "Repeat the Screwdriver inspection.",
                    ],
                    diagnostic_commands=["ros2 node list", "ros2 topic list -t"],
                    success_criteria=[
                        "The ROS graph is discovered and reports active nodes/topics."
                    ],
                )
            )
    return _deduplicate_issues(issues)


def _anthropic_analysis(
    snapshot: dict[str, Any],
    issues: list[DiagnosticIssue],
    *,
    model: str,
    effort: str,
    focus: str | None,
    probe_results: list[ProbeResult] | None = None,
) -> dict[str, Any]:
    api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        raise AgentProviderError("ANTHROPIC_API_KEY is not set")

    schema = _agent_schema()
    evidence = {
        "snapshot": _evidence_view(snapshot),
        "deterministic_issues": [issue.to_dict() for issue in issues],
        "focus": focus,
        "read_only_probe_results": [probe.to_dict() for probe in probe_results or []],
    }
    system = (
        "You are Screwdriver's robotics diagnostic engineer. Use only supplied evidence. "
        "Never claim hardware was tested, never invent facts, and distinguish verified, "
        "correlated, inferred, and unknown information. Preserve every deterministic issue. "
        "For each problem, provide ordered troubleshooting approaches and measurable success "
        "criteria. You may request only the listed read-only probes. Never recommend that the "
        "software execute repairs, actuator commands, permission changes, installs, restarts, "
        "or configuration edits automatically. Return JSON matching the supplied schema."
    )
    if probe_results:
        system += " Probe results are final evidence; do not request additional probes."
    user = (
        "Build (1) a concise system-blueprint narrative and (2) an evidence-grounded "
        "diagnostic plan. Allowed probes: ros_node_info, ros_topic_info, ros_param_list, "
        "device_metadata, port_owner, service_status, recent_kernel_logs, network_link.\n\n"
        + json.dumps(evidence, separators=(",", ":"))
    )
    payload = {
        "model": model,
        "max_tokens": _MAX_OUTPUT_TOKENS,
        "system": system,
        "messages": [
            {"role": "user", "content": user},
        ],
        "output_config": {
            "effort": effort,
            "format": {
                "type": "json_schema",
                "schema": schema,
            },
        },
    }
    request = urllib.request.Request(
        _ANTHROPIC_ENDPOINT,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "X-Api-Key": api_key,
            "Anthropic-Version": _ANTHROPIC_VERSION,
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=120) as response:  # noqa: S310
            body = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exception:
        raise AgentProviderError(_anthropic_http_error(exception)) from exception
    except (OSError, TimeoutError, urllib.error.URLError, json.JSONDecodeError) as exception:
        raise AgentProviderError(str(exception)) from exception

    response_body = _mapping(body)
    stop_reason = response_body.get("stop_reason")
    if stop_reason == "refusal":
        raise AgentProviderError("Claude refused the diagnostic request")
    if stop_reason == "max_tokens":
        raise AgentProviderError("Claude response reached the configured output limit")

    content = "".join(
        str(block.get("text") or "")
        for block in _records(response_body.get("content"))
        if block.get("type") == "text"
    )
    if not content:
        raise AgentProviderError("Claude returned no text content")
    try:
        result = json.loads(content)
    except json.JSONDecodeError as exception:
        raise AgentProviderError("Claude returned invalid structured JSON") from exception
    if not isinstance(result, dict):
        raise AgentProviderError("Claude result must be a JSON object")
    missing = {
        "summary",
        "architecture_observations",
        "unknowns",
        "issues",
        "probe_requests",
    } - result.keys()
    if missing:
        raise AgentProviderError(
            "Claude result is missing required fields: " + ", ".join(sorted(missing))
        )
    return cast(dict[str, Any], result)


def _anthropic_http_error(exception: urllib.error.HTTPError) -> str:
    """Return a bounded API error without exposing credentials or request content."""

    message = "request failed"
    try:
        body = json.loads(exception.read().decode("utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        pass
    else:
        error = _mapping(_mapping(body).get("error"))
        message = str(error.get("message") or message).strip()[:300]
    return f"Anthropic API HTTP {exception.code}: {message}"


def _agent_schema() -> dict[str, Any]:
    string_array = {"type": "array", "items": {"type": "string"}}
    return {
        "type": "object",
        "additionalProperties": False,
        "required": [
            "summary",
            "architecture_observations",
            "unknowns",
            "issues",
            "probe_requests",
        ],
        "properties": {
            "summary": {"type": "string"},
            "architecture_observations": string_array,
            "unknowns": string_array,
            "issues": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": [
                        "code",
                        "title",
                        "severity",
                        "confidence",
                        "evidence_level",
                        "observed",
                        "probable_causes",
                        "primary_approach",
                        "alternative_approaches",
                        "diagnostic_commands",
                        "success_criteria",
                    ],
                    "properties": {
                        "code": {"type": "string"},
                        "title": {"type": "string"},
                        "severity": {
                            "type": "string",
                            "enum": ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"],
                        },
                        "confidence": {
                            "type": "integer",
                            "description": "Confidence percentage from 0 through 100.",
                        },
                        "evidence_level": {
                            "type": "string",
                            "enum": ["VERIFIED", "CORRELATED", "INFERRED", "UNKNOWN"],
                        },
                        "observed": string_array,
                        "probable_causes": string_array,
                        "primary_approach": string_array,
                        "alternative_approaches": {
                            "type": "array",
                            "items": string_array,
                        },
                        "diagnostic_commands": string_array,
                        "success_criteria": string_array,
                    },
                },
            },
            "probe_requests": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["probe", "target", "reason"],
                    "properties": {
                        "probe": {"type": "string"},
                        "target": {"type": ["string", "null"]},
                        "reason": {"type": "string"},
                    },
                },
            },
        },
    }


def _evidence_view(snapshot: dict[str, Any]) -> dict[str, Any]:
    keep = (
        "schema_version",
        "created_at",
        "operating_system",
        "platform",
        "cpu",
        "memory",
        "storage_devices",
        "gpus",
        "thermal_sensors",
        "power",
        "network",
        "usb_devices",
        "serial_devices",
        "software_stack_inventory",
        "sensor_inventory",
        "actuator_inventory",
        "ros_device_inventory",
        "ros_runtime_inventory",
        "findings",
    )
    view = {key: snapshot.get(key) for key in keep}
    identity = _mapping(snapshot.get("identity"))
    view["identity"] = {"hostname": identity.get("hostname")}
    return cast(dict[str, Any], _bounded_value(view))


def _bounded_value(value: Any, depth: int = 0) -> Any:
    if depth > 7:
        return "[truncated]"
    if isinstance(value, str):
        return value[:1200]
    if isinstance(value, list):
        return [_bounded_value(item, depth + 1) for item in value[:100]]
    if isinstance(value, dict):
        redacted = {"machine_id", "serial_number", "mac_address", "default_gateway"}
        return {
            str(key): "[redacted]" if str(key) in redacted else _bounded_value(item, depth + 1)
            for key, item in value.items()
        }
    return value


def _parse_probe_requests(value: Any) -> list[ProbeRequest]:
    requests: list[ProbeRequest] = []
    for item in _records(value):
        probe = _clean_text(item.get("probe"))
        target = _clean_text(item.get("target"))
        reason = _clean_text(item.get("reason")) or "Additional evidence requested."
        if probe:
            requests.append(ProbeRequest(probe=probe, target=target, reason=reason))
    return requests[:_MAX_PROBES]


def _run_probe_requests(
    snapshot: dict[str, Any],
    requests: list[ProbeRequest],
) -> list[ProbeResult]:
    hostname = str(_mapping(snapshot.get("identity")).get("hostname") or "")
    if hostname and hostname not in {socket.gethostname(), socket.getfqdn()}:
        return []
    results: list[ProbeResult] = []
    for request in requests[:_MAX_PROBES]:
        command = _probe_command(request)
        if command is None:
            continue
        executable = shutil.which(command[0])
        if executable is None:
            results.append(
                ProbeResult(
                    request.probe,
                    request.target,
                    command,
                    "unavailable",
                    f"Required executable not found: {command[0]}",
                )
            )
            continue
        command = (executable, *command[1:])
        try:
            completed = subprocess.run(
                command,
                check=False,
                capture_output=True,
                text=True,
                timeout=5,
                env=os.environ.copy(),
            )
        except (OSError, subprocess.TimeoutExpired) as exception:
            results.append(
                ProbeResult(request.probe, request.target, command, "failed", str(exception))
            )
            continue
        output = (completed.stdout + completed.stderr).strip()[:_MAX_PROBE_OUTPUT]
        results.append(
            ProbeResult(
                request.probe,
                request.target,
                command,
                "completed" if completed.returncode == 0 else "nonzero",
                output or "Command returned no text.",
            )
        )
    return results


def _probe_command(request: ProbeRequest) -> tuple[str, ...] | None:
    target = request.target
    ros_name = re.compile(r"^/[A-Za-z0-9_~/.-]{1,160}$")
    device = re.compile(r"^/dev/[A-Za-z0-9_./-]{1,160}$")
    unit = re.compile(r"^[A-Za-z0-9@_.-]{1,120}$")
    interface = re.compile(r"^[A-Za-z0-9_.:-]{1,40}$")
    if request.probe == "ros_node_info" and target and ros_name.fullmatch(target):
        return ("ros2", "node", "info", target)
    if request.probe == "ros_topic_info" and target and ros_name.fullmatch(target):
        return ("ros2", "topic", "info", target, "--verbose")
    if request.probe == "ros_param_list" and target and ros_name.fullmatch(target):
        return ("ros2", "param", "list", target)
    if request.probe in {"device_metadata", "port_owner"} and target:
        if ".." in target or not device.fullmatch(target):
            return None
        return (
            ("udevadm", "info", "--query=property", "--name", target)
            if request.probe == "device_metadata"
            else ("lsof", "--", target)
        )
    if request.probe == "service_status" and target and unit.fullmatch(target):
        return ("systemctl", "--no-pager", "--full", "status", target)
    if request.probe == "recent_kernel_logs" and target is None:
        return ("journalctl", "--no-pager", "-k", "--since", "-10min", "-n", "150")
    if request.probe == "network_link" and target and interface.fullmatch(target):
        return ("ip", "-details", "link", "show", target)
    return None


def _merge_agent_issues(
    deterministic: list[DiagnosticIssue],
    value: Any,
) -> list[DiagnosticIssue]:
    by_code = {issue.code: issue for issue in deterministic}
    for record in _records(value):
        code = (_clean_text(record.get("code")) or "AGENT_INFERENCE").upper()
        existing = by_code.get(code)
        issue = DiagnosticIssue(
            code=code,
            title=_clean_text(record.get("title")) or (existing.title if existing else code),
            severity=_valid_severity(record.get("severity"), existing),
            confidence=_bounded_int(
                record.get("confidence"),
                existing.confidence if existing else 60,
            ),
            evidence_level=_valid_evidence_level(record.get("evidence_level"), existing),
            observed=_string_list(record.get("observed"))
            or (existing.observed if existing else []),
            probable_causes=_string_list(record.get("probable_causes"))
            or (existing.probable_causes if existing else []),
            primary_approach=_string_list(record.get("primary_approach"))
            or (existing.primary_approach if existing else []),
            alternative_approaches=[
                _string_list(item) for item in record.get("alternative_approaches", [])
            ]
            if isinstance(record.get("alternative_approaches"), list)
            else (existing.alternative_approaches if existing else []),
            diagnostic_commands=_safe_recommended_commands(
                _string_list(record.get("diagnostic_commands"))
            )
            or (existing.diagnostic_commands if existing else []),
            success_criteria=_string_list(record.get("success_criteria"))
            or (existing.success_criteria if existing else []),
        )
        if existing is None and not issue.observed:
            continue
        by_code[code] = issue
    return _deduplicate_issues(list(by_code.values()))


def _build_blueprint_html(
    snapshot: dict[str, Any],
    *,
    summary: str,
    observations: list[str],
    unknowns: list[str],
    provider_status: str,
    focus: str | None,
) -> str:
    identity = _mapping(snapshot.get("identity"))
    os_info = _mapping(snapshot.get("operating_system"))
    platform = _mapping(snapshot.get("platform"))
    cpu = _mapping(snapshot.get("cpu"))
    memory = _mapping(snapshot.get("memory"))
    ros = _ros_overview(snapshot)
    devices = _current_ros_device_names(snapshot)
    physical = [
        *_records(snapshot.get("usb_devices")),
        *_records(snapshot.get("serial_devices")),
    ]
    ros_runtime = _records(snapshot.get("ros_runtime_inventory"))
    node_rows = [item for item in ros_runtime if item.get("category") == "ROS node"]
    topic_rows = [item for item in ros_runtime if item.get("category") == "ROS topic"]
    service_rows = [item for item in ros_runtime if item.get("category") == "ROS service"]
    action_rows = [item for item in ros_runtime if item.get("category") == "ROS action"]
    ros_devices = _records(snapshot.get("ros_device_inventory"))
    software = _records(snapshot.get("software_stack_inventory"))
    network = _mapping(snapshot.get("network"))
    flow_rows = _flow_rows(ros_devices)
    architecture_rows = _architecture_rows(ros_devices)
    title = f"System blueprint — {identity.get('hostname', 'robot')}"
    return _html_page(
        title,
        f"""
<header class="hero">
  <span class="eyebrow">SCREWDRIVER · SYSTEM BLUEPRINT</span>
  <h1>{_h(title)}</h1>
  <p>{_h(summary)}</p>
  <div class="badges"><span>PASSIVE SNAPSHOT</span><span>{_h(provider_status)}</span>
  {_badge("Focus: " + focus) if focus else ""}</div>
</header>
<nav class="toc">
  <a href="#overview">Overview</a><a href="#architecture">Architecture</a>
  <a href="#hardware">Hardware</a><a href="#ros">ROS 2</a>
  <a href="#flows">Data flows</a><a href="#appendix">Appendix</a>
</nav>
<section id="overview"><h2>1. Executive overview</h2>
  <div class="metric-grid">
    {_metric("Compute", platform.get("product_name") or platform.get("board_name") or "Linux")}
    {_metric("OS", os_info.get("distribution"))}
    {_metric("ROS nodes", ros.get("nodes") if ros else 0)}
    {_metric("ROS topics", ros.get("topics") if ros else 0)}
    {_metric("Physical devices", len(physical))}
    {_metric("ROS devices in use", len(devices))}
  </div>
  <h3>Devices currently in use by ROS 2</h3>{_ordered_list(devices, empty="No device use was proven from the live graph.")}
</section>
<section id="architecture"><h2>2. System architecture</h2>
  <p class="muted">Physical device → Linux interface/driver → ROS node → endpoint → robot role.</p>
  {_table(["Physical component", "Linux / bus", "ROS node", "ROS endpoint", "Role", "Evidence"], architecture_rows)}
  <h3>Architecture observations</h3>{_unordered_list(observations)}
</section>
<section><h2>3. Main computer and processing hardware</h2>
  {_key_value_table({"Hostname": identity.get("hostname"), "Platform": platform.get("product_name") or platform.get("board_name"), "Manufacturer": platform.get("manufacturer"), "CPU": cpu.get("model"), "Logical CPUs": cpu.get("logical_cpus"), "Memory total": _bytes(memory.get("total_bytes")), "Memory usage": _percent(memory.get("usage_percent")), "GPU / accelerators": ", ".join(str(item.get("model")) for item in _records(snapshot.get("gpus"))) or "None detected"})}
</section>
<section><h2>4. Operating system and kernel</h2>
  {_key_value_table({"Distribution": os_info.get("distribution"), "Kernel": os_info.get("kernel"), "Architecture": os_info.get("architecture"), "Boot mode": os_info.get("boot_mode"), "Init system": os_info.get("init_system"), "System timezone": os_info.get("timezone"), "Report time": snapshot.get("created_at"), "Uptime seconds": os_info.get("uptime_seconds")})}
</section>
<section id="hardware"><h2>5. Complete physical hardware inventory</h2>
  <h3>USB devices</h3>{_component_table(_records(snapshot.get("usb_devices")), ("display_name", "usb_id", "device_class_name", "drivers"))}
  <h3>Serial / UART devices</h3>{_component_table(_records(snapshot.get("serial_devices")), ("display_name", "port", "transport", "driver", "stable_id_path"))}
  <h3>Storage</h3>{_component_table(_records(snapshot.get("storage_devices")), ("model", "path", "connection", "media_type", "capacity_bytes"))}
</section>
<section><h2>6. Current devices in use by ROS 2</h2>
  {_ordered_list(devices, empty="No hardware-facing ROS device was proven in use.")}
  {_ros_device_table(ros_devices)}
</section>
<section id="ros"><h2>7. ROS 2 environment</h2>{_key_value_table(ros or {"State": "No ROS runtime overview available"})}</section>
<section><h2>8. ROS 2 computational graph</h2>
  <div class="split"><div><h3>Nodes</h3>{_named_list(node_rows)}</div><div><h3>Topics</h3>{_named_list(topic_rows)}</div></div>
  <div class="split"><div><h3>Services</h3>{_named_list(service_rows)}</div><div><h3>Actions</h3>{_named_list(action_rows)}</div></div>
</section>
<section><h2>9. Motion and control architecture</h2>{_filtered_ros_devices(ros_devices, ("actuator", "controller", "mobile base", "gripper", "servo", "motor"))}</section>
<section><h2>10. Perception and navigation architecture</h2>{_filtered_ros_devices(ros_devices, ("camera", "lidar", "imu", "gps", "radar", "range", "navigation", "odometry"))}</section>
<section><h2>11. Audio, display, and human interaction</h2>{_filtered_ros_devices(ros_devices, ("microphone", "speaker", "audio", "display", "hmi", "touch"))}</section>
<section><h2>12. Network and communications blueprint</h2>
  {_key_value_table({"Default interface": network.get("default_interface"), "Internet route": network.get("internet_route_available"), "DNS servers": network.get("dns_servers")})}
  {_component_table(_records(network.get("interfaces")), ("name", "interface_type", "state", "ipv4_addresses", "speed_mbps", "driver"))}
</section>
<section><h2>13. Installed robotics software</h2>{_component_table(software, ("name", "status", "details"))}</section>
<section id="flows"><h2>14. Active data and command flows</h2>{_table(["Source / device", "ROS node", "Endpoint", "Direction", "Purpose"], flow_rows)}</section>
<section><h2>15. Unknowns and scan limitations</h2>{_unordered_list(unknowns, empty="No explicit unknowns were recorded.")}
  <p class="callout">The scan used metadata only. Sensor streams were not sampled, actuators were not commanded, and component behavior was not functionally tested.</p>
</section>
<section id="appendix"><h2>16. Detailed technical appendix</h2>
  {_details("Complete ROS graph records", ros_runtime)}
  {_details("Complete USB inventory", snapshot.get("usb_devices"))}
  {_details("Complete serial inventory", snapshot.get("serial_devices"))}
  {_details("Collection findings", snapshot.get("findings"))}
</section>
""",
    )


def _build_diagnostic_html(
    snapshot: dict[str, Any],
    *,
    issues: list[DiagnosticIssue],
    probes: list[ProbeResult],
    provider_status: str,
) -> str:
    identity = _mapping(snapshot.get("identity"))
    severity_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
    issues = sorted(issues, key=lambda issue: severity_order.get(issue.severity, 9))
    cards = "".join(_issue_card(issue, index) for index, issue in enumerate(issues, 1))
    if not cards:
        cards = (
            '<div class="empty"><h3>No actionable failures detected</h3>'
            "<p>The snapshot contains no warning/error findings. This does not prove every "
            "physical function was exercised.</p></div>"
        )
    counts = {
        severity: sum(issue.severity == severity for issue in issues) for severity in severity_order
    }
    probe_html = ""
    if probes:
        probe_html = (
            "<section><h2>Read-only investigation evidence</h2>"
            + "".join(
                f"<details><summary>{_h(probe.probe)} · {_h(probe.target or 'system')}</summary>"
                f"<p>Status: {_h(probe.state)}</p><pre>{_h(probe.output)}</pre></details>"
                for probe in probes
            )
            + "</section>"
        )
    title = f"Diagnostic report — {identity.get('hostname', 'robot')}"
    return _html_page(
        title,
        f"""
<header class="hero diagnostic">
  <span class="eyebrow">SCREWDRIVER · FAILURE / BUG / MISCONFIGURATION REPORT</span>
  <h1>{_h(title)}</h1>
  <p>Evidence-grounded problems, likely causes, and ordered troubleshooting approaches.</p>
  <div class="badges"><span>NO REPAIRS EXECUTED</span><span>{_h(provider_status)}</span></div>
</header>
<section><h2>Diagnostic overview</h2>
  <div class="metric-grid">{_metric("Critical", counts["CRITICAL"])}{_metric("High", counts["HIGH"])}{_metric("Medium", counts["MEDIUM"])}{_metric("Low", counts["LOW"])}{_metric("Read-only probes", len(probes))}</div>
  <p class="callout">Recommendations are instructions for a human engineer. Screwdriver did not install packages, edit configuration, restart services, change permissions, publish ROS commands, or move hardware.</p>
</section>
<section><h2>Problems and step-by-step solutions</h2>{cards}</section>
{probe_html}
<section><h2>Verification checklist</h2>
  <ol><li>Apply only one approved change at a time.</li><li>Repeat the original failing check.</li><li>Run a new passive inspection.</li><li>Compare the new snapshot with this report.</li><li>Confirm no new warnings or regressions appeared.</li></ol>
</section>
""",
    )


def _issue_card(issue: DiagnosticIssue, index: int) -> str:
    alternatives = "".join(
        f"<h4>Alternative approach {number}</h4>{_ordered_list(steps)}"
        for number, steps in enumerate(issue.alternative_approaches, 1)
        if steps
    )
    commands = ""
    if issue.diagnostic_commands:
        commands = "<h4>Diagnostic commands</h4>" + "".join(
            f"<pre><code>{_h(command)}</code></pre>" for command in issue.diagnostic_commands
        )
    return f"""
<article class="issue severity-{issue.severity.lower()}">
  <div class="issue-head"><span class="issue-number">{index}</span><div><h3>{_h(issue.title)}</h3>
  <p><strong>{_h(issue.severity)}</strong> · {issue.confidence}% confidence · {_h(issue.evidence_level)}</p></div></div>
  <h4>Observed evidence</h4>{_unordered_list(issue.observed)}
  <h4>Probable causes</h4>{_ordered_list(issue.probable_causes)}
  <h4>Primary step-by-step approach</h4>{_ordered_list(issue.primary_approach)}
  {alternatives}{commands}
  <h4>Success criteria</h4>{_unordered_list(issue.success_criteria)}
</article>
"""


def _html_page(title: str, body: str) -> str:
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{_h(title)}</title><style>
:root{{--bg:#08111f;--panel:#101d30;--panel2:#14243a;--line:#2a3c57;--text:#eef5ff;--muted:#a9bad0;--cyan:#58d3ff;--green:#5ee6a8;--amber:#ffc857;--red:#ff6b7a}}
*{{box-sizing:border-box}}body{{margin:0;background:radial-gradient(circle at top right,#123255 0,#08111f 38%);color:var(--text);font:15px/1.55 Inter,system-ui,sans-serif}}main{{max-width:1180px;margin:auto;padding:38px 22px 80px}}h1{{font-size:clamp(2rem,5vw,4.2rem);line-height:1.04;margin:.3rem 0 1rem}}h2{{margin-top:0;font-size:1.65rem}}h3{{margin-top:1.4rem}}section,.hero,.toc{{background:#101d30e8;border:1px solid var(--line);border-radius:18px;padding:24px;margin:18px 0;box-shadow:0 20px 55px #0004}}.hero{{padding:38px;background:linear-gradient(135deg,#102840,#101d30)}}.hero.diagnostic{{background:linear-gradient(135deg,#351d2c,#101d30)}}.eyebrow{{letter-spacing:.18em;color:var(--cyan);font-weight:800;font-size:.75rem}}.muted,.issue p{{color:var(--muted)}}.badges{{display:flex;gap:8px;flex-wrap:wrap}}.badges span{{border:1px solid #3e5879;border-radius:999px;padding:5px 10px;font-size:.75rem}}.toc{{display:flex;gap:18px;flex-wrap:wrap;position:sticky;top:8px;z-index:2;padding:12px 20px}}a{{color:var(--cyan)}}.metric-grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:12px}}.metric{{background:var(--panel2);border:1px solid var(--line);border-radius:14px;padding:16px}}.metric strong{{display:block;font-size:1.35rem;color:var(--green)}}table{{width:100%;border-collapse:collapse;display:block;overflow-x:auto}}th,td{{padding:10px 12px;border:1px solid var(--line);text-align:left;vertical-align:top;max-width:440px}}th{{background:#182a43;color:#dcecff}}pre{{white-space:pre-wrap;word-break:break-word;background:#07101d;border:1px solid var(--line);border-radius:10px;padding:13px;overflow:auto}}.split{{display:grid;grid-template-columns:1fr 1fr;gap:18px}}.callout{{border-left:4px solid var(--amber);background:#211f20;padding:14px 16px;border-radius:8px}}.issue{{border:1px solid var(--line);border-left:6px solid var(--amber);border-radius:14px;padding:20px;margin:18px 0;background:#0d1828}}.severity-critical,.severity-high{{border-left-color:var(--red)}}.severity-low,.severity-info{{border-left-color:var(--cyan)}}.issue-head{{display:flex;gap:14px;align-items:flex-start}}.issue-number{{display:grid;place-items:center;min-width:34px;height:34px;background:#20344f;border-radius:50%;font-weight:800}}.issue-head h3{{margin:0}}details{{border:1px solid var(--line);padding:12px;border-radius:10px;margin:10px 0}}summary{{cursor:pointer;font-weight:700}}.empty{{padding:24px;border:1px dashed var(--line);border-radius:12px}}@media(max-width:700px){{.split{{grid-template-columns:1fr}}.toc{{position:static}}section,.hero{{padding:18px}}}}
</style></head><body><main>{body}<footer class="muted">Generated from passive evidence. Facts, correlations, inferences, and unknowns remain explicitly separated.</footer></main></body></html>"""


def _architecture_rows(devices: list[dict[str, Any]]) -> list[list[Any]]:
    rows: list[list[Any]] = []
    for device in devices:
        details = _mapping(device.get("details"))
        rows.append(
            [
                details.get("physical_component") or "Unresolved",
                details.get("physical_channel")
                or details.get("physical_bus")
                or details.get("bus"),
                details.get("ros_node") or details.get("hardware_node"),
                details.get("topics") or details.get("channel") or details.get("ros_endpoint"),
                details.get("kind") or device.get("name"),
                details.get("confidence") or "UNKNOWN",
            ]
        )
    return rows


def _flow_rows(devices: list[dict[str, Any]]) -> list[list[Any]]:
    rows: list[list[Any]] = []
    for device in devices:
        details = _mapping(device.get("details"))
        rows.append(
            [
                details.get("physical_component") or details.get("kind") or device.get("name"),
                details.get("ros_node") or details.get("hardware_node"),
                details.get("topics") or details.get("channel") or details.get("ros_endpoint"),
                details.get("direction"),
                details.get("kind"),
            ]
        )
    return rows


def _current_ros_device_names(snapshot: dict[str, Any]) -> list[str]:
    aliases = {
        "camera": "Camera",
        "lidar": "LiDAR",
        "point-cloud sensor": "Point-cloud sensor",
        "imu": "IMU",
        "gps/gnss": "GPS/GNSS",
        "microphone": "Microphone",
        "microphone / audio capture": "Microphone",
        "speaker / audio output": "Speaker",
        "display / visual output": "Display unit",
        "mobile base drive": "Mobile base",
        "motor / actuator controller": "Motor / actuator",
        "gripper": "Gripper",
        "power / battery device": "Battery / power system",
    }
    names: list[str] = []
    for device in _records(snapshot.get("ros_device_inventory")):
        details = _mapping(device.get("details"))
        if str(details.get("state") or "").upper() not in {"IN_USE_BY_ROS", "ACTIVE", "RUNNING"}:
            continue
        kind = str(details.get("kind") or device.get("name") or "Other ROS device")
        names.append(aliases.get(kind.lower(), kind.replace("_", " ").capitalize()))
    return _deduplicate_text(names)


def _ros_overview(snapshot: dict[str, Any]) -> dict[str, Any]:
    for item in _records(snapshot.get("ros_runtime_inventory")):
        if item.get("category") == "ROS runtime":
            return _mapping(item.get("details"))
    return {}


def _ros_device_table(devices: list[dict[str, Any]]) -> str:
    return _table(
        [
            "Device",
            "Class",
            "ROS node",
            "Topics / channel",
            "Physical match",
            "Driver",
            "Confidence",
        ],
        [
            [
                _mapping(item.get("details")).get("kind") or item.get("name"),
                _mapping(item.get("details")).get("device_class"),
                _mapping(item.get("details")).get("ros_node"),
                _mapping(item.get("details")).get("topics")
                or _mapping(item.get("details")).get("channel"),
                _mapping(item.get("details")).get("physical_component"),
                _mapping(item.get("details")).get("driver"),
                _mapping(item.get("details")).get("confidence"),
            ]
            for item in devices
        ],
    )


def _filtered_ros_devices(devices: list[dict[str, Any]], terms: tuple[str, ...]) -> str:
    selected = [item for item in devices if any(term in json.dumps(item).lower() for term in terms)]
    return (
        _ros_device_table(selected)
        if selected
        else '<p class="muted">No matching active architecture was identified.</p>'
    )


def _component_table(records: list[dict[str, Any]], keys: tuple[str, ...]) -> str:
    if not records:
        return '<p class="muted">No items detected.</p>'
    return _table(
        [key.replace("_", " ").title() for key in keys],
        [[record.get(key) for key in keys] for record in records],
    )


def _named_list(records: list[dict[str, Any]]) -> str:
    return _unordered_list([str(item.get("name") or "Unnamed") for item in records])


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    if not rows:
        return '<p class="muted">No records available.</p>'
    head = "".join(f"<th>{_h(value)}</th>" for value in headers)
    body = "".join(
        "<tr>" + "".join(f"<td>{_h(_display(value))}</td>" for value in row) + "</tr>"
        for row in rows
    )
    return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"


def _key_value_table(values: dict[str, Any]) -> str:
    return _table(["Property", "Value"], [[key, value] for key, value in values.items()])


def _ordered_list(values: list[str], *, empty: str = "No items available.") -> str:
    return (
        f"<ol>{''.join(f'<li>{_h(value)}</li>' for value in values)}</ol>"
        if values
        else f'<p class="muted">{_h(empty)}</p>'
    )


def _unordered_list(values: list[str], *, empty: str = "No items available.") -> str:
    return (
        f"<ul>{''.join(f'<li>{_h(value)}</li>' for value in values)}</ul>"
        if values
        else f'<p class="muted">{_h(empty)}</p>'
    )


def _metric(label: str, value: Any) -> str:
    return (
        f'<div class="metric"><span>{_h(label)}</span><strong>{_h(_display(value))}</strong></div>'
    )


def _badge(value: str) -> str:
    return f"<span>{_h(value)}</span>"


def _details(label: str, value: Any) -> str:
    return f"<details><summary>{_h(label)}</summary><pre>{_h(json.dumps(value, indent=2))}</pre></details>"


def _records(value: Any) -> list[dict[str, Any]]:
    if not isinstance(value, list):
        return []
    return [cast(dict[str, Any], item) for item in value if isinstance(item, dict)]


def _mapping(value: Any) -> dict[str, Any]:
    return cast(dict[str, Any], value) if isinstance(value, dict) else {}


def _clean_text(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _string_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [text for item in value if (text := _clean_text(item))]


def _display(value: Any) -> str:
    if value is None or value == "":
        return "Unknown"
    if isinstance(value, (list, dict)):
        return json.dumps(value, ensure_ascii=False)
    return str(value)


def _h(value: Any) -> str:
    return html.escape(str(value), quote=True)


def _bytes(value: Any) -> str:
    if not isinstance(value, (int, float)):
        return "Unknown"
    amount = float(value)
    for unit in ("B", "KiB", "MiB", "GiB", "TiB"):
        if amount < 1024 or unit == "TiB":
            return f"{amount:.1f} {unit}"
        amount /= 1024
    return "Unknown"


def _percent(value: Any) -> str:
    return f"{float(value):.1f}%" if isinstance(value, (int, float)) else "Unknown"


def _severity_label(value: str) -> str:
    return {"error": "HIGH", "warning": "MEDIUM", "info": "INFO"}.get(value, "LOW")


def _valid_severity(value: Any, existing: DiagnosticIssue | None) -> str:
    text = str(value or "").upper()
    return (
        text
        if text in {"CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"}
        else (existing.severity if existing else "LOW")
    )


def _valid_evidence_level(value: Any, existing: DiagnosticIssue | None) -> str:
    text = str(value or "").upper()
    return (
        text
        if text in {"VERIFIED", "CORRELATED", "INFERRED", "UNKNOWN"}
        else (existing.evidence_level if existing else "INFERRED")
    )


def _bounded_int(value: Any, default: int) -> int:
    try:
        return max(0, min(100, int(value)))
    except (TypeError, ValueError):
        return default


def _recommendation_steps(recommendation: str | None, code: str) -> list[str]:
    if recommendation:
        parts = [part.strip(" .") for part in re.split(r"(?:\n|;|(?<=\.)\s+)", recommendation)]
        steps = [part + "." for part in parts if part]
        if steps:
            return steps
    return [
        "Confirm the observation using the listed read-only diagnostic commands.",
        f"Inspect the configuration or component associated with {code}.",
        "Apply one human-approved correction.",
        "Repeat the check and confirm the success criteria.",
    ]


def _default_cause(code: str) -> str:
    categories = {
        "ROS_": "ROS environment, discovery, endpoint, or configuration inconsistency.",
        "SERIAL_": "Serial identity, driver binding, permissions, or port ownership inconsistency.",
        "CPU_": "Sustained workload, runaway process, or insufficient compute headroom.",
        "MEMORY_": "Application growth, memory leak, cache pressure, or insufficient RAM.",
        "FILESYSTEM_": "Logs, datasets, containers, or application files consumed available storage.",
        "THERMAL_": "Cooling, airflow, workload, fan control, or thermal-interface problem.",
    }
    return next(
        (text for prefix, text in categories.items() if code.startswith(prefix)),
        "A component or configuration does not match the expected operating state.",
    )


def _commands_for_code(code: str, finding: dict[str, Any]) -> list[str]:
    evidence = str(finding.get("evidence") or "")
    if code.startswith("ROS_"):
        return ["ros2 node list", "ros2 topic list -t"]
    if code.startswith("SERIAL_"):
        match = re.search(
            r"/dev/[A-Za-z0-9_./-]+", evidence + " " + str(finding.get("summary") or "")
        )
        port = match.group(0) if match else "/dev/ttyUSB0"
        return [f"udevadm info --query=property --name {port}", f"lsof -- {port}"]
    if code.startswith(("CPU_", "MEMORY_")):
        return ["ps -eo pid,comm,%cpu,%mem --sort=-%cpu | head -20"]
    if code.startswith("FILESYSTEM_"):
        return ["df -hT", "du -xhd1 /var 2>/dev/null | sort -h"]
    if code.startswith("THERMAL_"):
        return ["sensors", "cat /sys/class/thermal/thermal_zone*/temp"]
    return []


def _success_for_code(code: str) -> str:
    if code.startswith("ROS_"):
        return (
            "The expected ROS nodes and endpoints are visible with consistent environment settings."
        )
    if code.startswith("SERIAL_"):
        return "The intended process can identify and access the stable serial device without contention."
    if code.startswith("CPU_"):
        return "CPU usage remains below the warning threshold under the expected workload."
    if code.startswith("MEMORY_"):
        return "Memory usage remains below the warning threshold without growth over time."
    if code.startswith("FILESYSTEM_"):
        return "The affected filesystem has sufficient free capacity for logs and runtime data."
    if code.startswith("THERMAL_"):
        return "Temperature remains below the platform limit during the expected workload."
    return "A repeat inspection no longer reports this finding."


def _safe_recommended_commands(commands: list[str]) -> list[str]:
    blocked = re.compile(
        r"\b(sudo|rm|mv|cp|chmod|chown|apt|dnf|yum|pacman|pip install|systemctl restart|"
        r"systemctl stop|kill|pkill|reboot|shutdown|ros2 topic pub|ros2 service call)\b",
        re.IGNORECASE,
    )
    return [command for command in commands if not blocked.search(command)]


def _deduplicate_text(values: list[str]) -> list[str]:
    output: list[str] = []
    seen: set[str] = set()
    for value in values:
        key = value.casefold()
        if key not in seen:
            seen.add(key)
            output.append(value)
    return output


def _deduplicate_issues(issues: list[DiagnosticIssue]) -> list[DiagnosticIssue]:
    result: list[DiagnosticIssue] = []
    seen: set[str] = set()
    for issue in issues:
        if issue.code not in seen:
            seen.add(issue.code)
            result.append(issue)
    return result
